### ISSUE TITLE
Define project structure

### ISSUE THREAD

**Issue by rossanodan** [EddieJaoudeCommunity/EddieBotUI#3]
This is a basic architecture I'd like to propose

```
./src
  ./components <-- shared and reusable components
  ./pages <-- bigger components that, eventually, handle some state
  index.js <-- entry point
  App.js <-- outer component that handles the routing
  ...
```

Thinking about the architecture is a crucial point in this phase. We have to do our best to keep the complexity at the minimum keeping it highly scalable.

**Comment by eddiejaoude** [comment]
I am not familiar with `React` to know the best practice conventions. I will go with your recommendations 🤓

**Comment by BOLT04** [comment]
@rossanodan that folder structure seems good to me 👍. I like the idea of then inside `/pages` doing **Feature-based** structuring, but I'm not quite sure it fits this application yet, since we don't have much planned.

I'd also like to know if we'll use just CSS or something like SCSS. I prefer SCSS but I'd like to know everyone's opinion.

**Comment by eddiejaoude** [comment]
My 2 cents on the `css` vs `scss`, is I prefer `scss` - must be the `angular` in me 🤓

**Comment by rossanodan** [comment]
@BOLT04 and @eddiejaoude SCSS already setup ;)

**Comment by eddiejaoude** [comment]
Nice 👍
