### ISSUE TITLE
Current EddieHub's Discord link is invalid

### ISSUE THREAD

**Issue by ShaileshKumar007** [EddieJaoudeCommunity/EddieBotUI#48]
**Describe the bug**
In the Readme.md, when we click on link to join EddiHub on Discord then it shows the invalid invite link.

**To Reproduce**
1. Go to 'README.md' file
2. Scroll down to 'About EddieBotUI'
3. Click on 'click to join'

**Expected behavior**
It should direct everyone to the Discord's website where we should see invite link of EddieHub's Discord server

**Screenshots**
![eddie discord](https://user-images.githubusercontent.com/71178959/132092681-aef2c07e-8d78-4096-b026-d2c6246c0746.JPG)

**Desktop (please complete the following information):**
 - OS: All OS
 - Browser : All Browsers
 - Version : All Versions

**Smartphone (please complete the following information):**
 - Device: All Devices
 - OS: All OS
 - Browser: All Browsers
 - Version: All Versions

**Additional context**

**Comment by ahmedou-yahya** [comment]
Hi @ShaileshKumar007,

I think the problem is the invite link keeps expiring. Because by default, Discord invite links expires after 24 hours. This means that if the owner of the server didn’t edit the invite link’s expiration date, it’ll expire after 24 hours.

As a server owner, you’re given the ability to edit your invite link settings.This can be found on  server’s menu > invite > settings.

The expiration date settings is located under “Advanced Settings”. Under “Expire After”, you can choose to set the invite link to “Never”, “1 day”, “12 hours”, “6 hours”, “1 hour”, or “30 mins”.

**Comment by ShaileshKumar007** [comment]
Thank you @ahmedou-yahya for this information, I didn't know about this earlier.
